[package]
name = "compute-starter-kit-rust-default"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
anyhow = "^1.0"
fastly = "^0.7"
log = "^0.4"
log-fastly = "^0.2"